# Generated by Django 5.2.4 on 2025-07-17 20:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_initial'),
        ('settings', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverycompany',
            options={'ordering': ['name_en'], 'verbose_name': 'Delivery Company', 'verbose_name_plural': 'Delivery Companies'},
        ),
        migrations.AlterModelOptions(
            name='deliveryrecord',
            options={'ordering': ['-assigned_at'], 'verbose_name': 'Delivery Record', 'verbose_name_plural': 'Delivery Records'},
        ),
        migrations.RemoveField(
            model_name='deliveryrecord',
            name='driver',
        ),
        migrations.AddField(
            model_name='deliverycompany',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='deliverycompany',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='deliverycompany',
            name='webhook_url',
            field=models.URLField(blank=True, verbose_name='Webhook URL'),
        ),
        migrations.AddField(
            model_name='deliveryrecord',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Accepted At'),
        ),
        migrations.AddField(
            model_name='deliveryrecord',
            name='actual_delivery_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Actual Delivery Time'),
        ),
        migrations.AddField(
            model_name='deliveryrecord',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='deliveryrecord',
            name='customer_feedback',
            field=models.TextField(blank=True, verbose_name='Customer Feedback'),
        ),
        migrations.AddField(
            model_name='deliveryrecord',
            name='customer_rating',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Customer Rating'),
        ),
        migrations.AddField(
            model_name='deliveryrecord',
            name='customer_signature',
            field=models.TextField(blank=True, verbose_name='Customer Signature'),
        ),
        migrations.AddField(
            model_name='deliveryrecord',
            name='delivery_proof_photo',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_proof/', verbose_name='Delivery Proof Photo'),
        ),
        migrations.AddField(
            model_name='deliveryrecord',
            name='estimated_delivery_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Estimated Delivery Time'),
        ),
        migrations.AddField(
            model_name='deliveryrecord',
            name='estimated_pickup_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Estimated Pickup Time'),
        ),
        migrations.AddField(
            model_name='deliveryrecord',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Failed At'),
        ),
        migrations.AddField(
            model_name='deliveryrecord',
            name='out_for_delivery_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Out for Delivery At'),
        ),
        migrations.AddField(
            model_name='deliveryrecord',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10, verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='deliveryrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='deliverycompany',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='deliverycompany',
            name='api_secret',
            field=models.CharField(blank=True, max_length=255, verbose_name='API Secret'),
        ),
        migrations.AlterField(
            model_name='deliverycompany',
            name='base_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Base Delivery Cost'),
        ),
        migrations.AlterField(
            model_name='deliverycompany',
            name='countries',
            field=models.ManyToManyField(blank=True, to='settings.country'),
        ),
        migrations.AlterField(
            model_name='deliverycompany',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='deliverycompany',
            name='name_ar',
            field=models.CharField(max_length=100, verbose_name='Company Name (Arabic)'),
        ),
        migrations.AlterField(
            model_name='deliverycompany',
            name='name_en',
            field=models.CharField(max_length=100, verbose_name='Company Name (English)'),
        ),
        migrations.AlterField(
            model_name='deliveryrecord',
            name='assigned_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Assigned At'),
        ),
        migrations.AlterField(
            model_name='deliveryrecord',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Delivered At'),
        ),
        migrations.AlterField(
            model_name='deliveryrecord',
            name='delivery_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='delivery.deliverycompany'),
        ),
        migrations.AlterField(
            model_name='deliveryrecord',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Delivery Cost'),
        ),
        migrations.AlterField(
            model_name='deliveryrecord',
            name='delivery_notes',
            field=models.TextField(blank=True, verbose_name='Delivery Notes'),
        ),
        # Removed: migrations.AlterField for DeliveryRecord.id from BigAutoField to UUIDField
        # This causes PostgreSQL errors - cannot cast bigint to uuid
        # Keeping BigAutoField for DeliveryRecord.id
        migrations.AlterField(
            model_name='deliveryrecord',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Picked Up At'),
        ),
        migrations.AlterField(
            model_name='deliveryrecord',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('accepted', 'Accepted'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('attempted', 'Delivery Attempted'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='assigned', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='deliveryrecord',
            name='tracking_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Tracking Number'),
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True, verbose_name='Employee ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('vehicle_type', models.CharField(blank=True, max_length=50, verbose_name='Vehicle Type')),
                ('vehicle_number', models.CharField(blank=True, max_length=20, verbose_name='Vehicle Number')),
                ('license_number', models.CharField(blank=True, max_length=50, verbose_name='License Number')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('on_leave', 'On Leave')], default='active', max_length=20, verbose_name='Status')),
                ('availability', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('offline', 'Offline'), ('break', 'On Break')], default='offline', max_length=20, verbose_name='Availability')),
                ('max_daily_deliveries', models.PositiveIntegerField(default=50, verbose_name='Max Daily Deliveries')),
                ('current_location_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Current Latitude')),
                ('current_location_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Current Longitude')),
                ('last_location_update', models.DateTimeField(blank=True, null=True, verbose_name='Last Location Update')),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('total_deliveries', models.PositiveIntegerField(default=0, verbose_name='Total Deliveries')),
                ('successful_deliveries', models.PositiveIntegerField(default=0, verbose_name='Successful Deliveries')),
                ('failed_deliveries', models.PositiveIntegerField(default=0, verbose_name='Failed Deliveries')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couriers', to='delivery.deliverycompany')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='courier_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Courier',
                'verbose_name_plural': 'Couriers',
                'ordering': ['user__full_name'],
            },
        ),
        migrations.AddField(
            model_name='deliveryrecord',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='delivery.courier'),
        ),
        migrations.CreateModel(
            name='CourierLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Longitude')),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Accuracy (meters)')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('battery_level', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Battery Level (%)')),
                ('connection_type', models.CharField(choices=[('wifi', 'WiFi'), ('cellular', 'Cellular'), ('offline', 'Offline')], default='cellular', max_length=20, verbose_name='Connection Type')),
                ('speed', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Speed (km/h)')),
                ('heading', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Heading (degrees)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='delivery.courier')),
            ],
            options={
                'verbose_name': 'Courier Location',
                'verbose_name_plural': 'Courier Locations',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CourierSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Login Time')),
                ('logout_time', models.DateTimeField(blank=True, null=True, verbose_name='Logout Time')),
                ('status', models.CharField(choices=[('active', 'Active'), ('break', 'Break'), ('offline', 'Offline')], default='active', max_length=20, verbose_name='Status')),
                ('location_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Location Latitude')),
                ('location_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Location Longitude')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Last Activity')),
                ('device_info', models.TextField(blank=True, verbose_name='Device Information')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='delivery.courier')),
            ],
            options={
                'verbose_name': 'Courier Session',
                'verbose_name_plural': 'Courier Sessions',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(default=1, verbose_name='Attempt Number')),
                ('attempt_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Attempt Time')),
                ('result', models.CharField(choices=[('successful', 'Successful'), ('failed', 'Failed'), ('rescheduled', 'Rescheduled')], max_length=20, verbose_name='Result')),
                ('failure_reason', models.CharField(blank=True, choices=[('customer_not_available', 'Customer Not Available'), ('wrong_address', 'Wrong Address'), ('customer_refused', 'Customer Refused'), ('package_damaged', 'Package Damaged'), ('weather_conditions', 'Weather Conditions'), ('vehicle_breakdown', 'Vehicle Breakdown'), ('traffic_delay', 'Traffic Delay'), ('other', 'Other')], max_length=30, null=True, verbose_name='Failure Reason')),
                ('customer_feedback', models.TextField(blank=True, verbose_name='Customer Feedback')),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='delivery_attempts/', verbose_name='Proof Image')),
                ('signature_data', models.TextField(blank=True, verbose_name='Signature Data')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('next_attempt_date', models.DateTimeField(blank=True, null=True, verbose_name='Next Attempt Date')),
                ('location_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Location Latitude')),
                ('location_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Location Longitude')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='delivery.courier')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='delivery.deliveryrecord')),
            ],
            options={
                'verbose_name': 'Delivery Attempt',
                'verbose_name_plural': 'Delivery Attempts',
                'ordering': ['-attempt_time'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_type', models.CharField(choices=[('photo', 'Photo'), ('signature', 'Signature'), ('barcode', 'Barcode Scan'), ('otp', 'OTP Verification'), ('gps', 'GPS Location')], max_length=20, verbose_name='Proof Type')),
                ('proof_data', models.TextField(verbose_name='Proof Data')),
                ('capture_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Capture Time')),
                ('location_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Location Latitude')),
                ('location_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Location Longitude')),
                ('verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verified At')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_proofs', to='delivery.courier')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='delivery.deliveryrecord')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_proofs', to=settings.AUTH_USER_MODEL, verbose_name='Verified By')),
            ],
            options={
                'verbose_name': 'Delivery Proof',
                'verbose_name_plural': 'Delivery Proofs',
                'ordering': ['-capture_time'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('accepted', 'Accepted'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('attempted', 'Delivery Attempted'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='delivery.deliveryrecord')),
            ],
            options={
                'verbose_name': 'Delivery Status History',
                'verbose_name_plural': 'Delivery Status Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('total_deliveries', models.PositiveIntegerField(default=0, verbose_name='Total Deliveries')),
                ('successful_deliveries', models.PositiveIntegerField(default=0, verbose_name='Successful Deliveries')),
                ('failed_deliveries', models.PositiveIntegerField(default=0, verbose_name='Failed Deliveries')),
                ('total_distance', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Total Distance (km)')),
                ('total_time', models.PositiveIntegerField(default=0, verbose_name='Total Time (minutes)')),
                ('average_delivery_time', models.PositiveIntegerField(default=0, verbose_name='Average Delivery Time (minutes)')),
                ('customer_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Average Customer Rating')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='delivery.courier')),
            ],
            options={
                'verbose_name': 'Delivery Performance',
                'verbose_name_plural': 'Delivery Performances',
                'ordering': ['-date'],
                'unique_together': {('courier', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DeliveryRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_date', models.DateField(verbose_name='Route Date')),
                ('route_name', models.CharField(max_length=100, verbose_name='Route Name')),
                ('total_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Total Distance (km)')),
                ('estimated_duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Estimated Duration (minutes)')),
                ('route_data', models.JSONField(default=dict, verbose_name='Route Data')),
                ('is_optimized', models.BooleanField(default=False, verbose_name='Optimized')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='delivery.courier')),
            ],
            options={
                'verbose_name': 'Delivery Route',
                'verbose_name_plural': 'Delivery Routes',
                'ordering': ['-route_date'],
                'unique_together': {('courier', 'route_date')},
            },
        ),
    ]
