# Generated by Django 5.2.8 on 2025-12-02 13:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delivery", "0007_add_manager_confirmation_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliverySecuritySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "otp_enabled",
                    models.BooleanField(default=True, verbose_name="OTP Enabled"),
                ),
                (
                    "otp_length",
                    models.PositiveIntegerField(
                        default=6,
                        validators=[
                            django.core.validators.MinValueValidator(4),
                            django.core.validators.MaxValueValidator(8),
                        ],
                        verbose_name="OTP Length",
                    ),
                ),
                (
                    "otp_expiry_minutes",
                    models.PositiveIntegerField(
                        default=15, verbose_name="OTP Expiry (minutes)"
                    ),
                ),
                (
                    "otp_max_attempts",
                    models.PositiveIntegerField(
                        default=3, verbose_name="OTP Max Attempts"
                    ),
                ),
                (
                    "pin_enabled",
                    models.BooleanField(default=True, verbose_name="PIN Enabled"),
                ),
                (
                    "pin_length",
                    models.PositiveIntegerField(
                        default=4,
                        validators=[
                            django.core.validators.MinValueValidator(4),
                            django.core.validators.MaxValueValidator(6),
                        ],
                        verbose_name="PIN Length",
                    ),
                ),
                (
                    "pin_validity_days",
                    models.PositiveIntegerField(
                        default=7, verbose_name="PIN Validity (days)"
                    ),
                ),
                (
                    "geofencing_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Geofencing Enabled"
                    ),
                ),
                (
                    "default_geofence_radius",
                    models.PositiveIntegerField(
                        default=100, verbose_name="Default Geofence Radius (meters)"
                    ),
                ),
                (
                    "strict_geofencing",
                    models.BooleanField(
                        default=False,
                        help_text="Block deliveries outside geofence",
                        verbose_name="Strict Geofencing",
                    ),
                ),
                (
                    "photo_verification_required",
                    models.BooleanField(
                        default=True, verbose_name="Photo Verification Required"
                    ),
                ),
                (
                    "photo_max_size_mb",
                    models.PositiveIntegerField(
                        default=10, verbose_name="Photo Max Size (MB)"
                    ),
                ),
                (
                    "fraud_detection_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Fraud Detection Enabled"
                    ),
                ),
                (
                    "fraud_alert_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=70.0,
                        help_text="Alert when confidence > this %",
                        max_digits=5,
                        verbose_name="Fraud Alert Threshold",
                    ),
                ),
                (
                    "auto_block_high_risk",
                    models.BooleanField(
                        default=False, verbose_name="Auto-block High Risk Deliveries"
                    ),
                ),
                (
                    "notify_security_team",
                    models.BooleanField(
                        default=True, verbose_name="Notify Security Team"
                    ),
                ),
                (
                    "security_team_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Security Team Email"
                    ),
                ),
                (
                    "log_all_events",
                    models.BooleanField(
                        default=True, verbose_name="Log All Security Events"
                    ),
                ),
                (
                    "retention_days",
                    models.PositiveIntegerField(
                        default=90, verbose_name="Log Retention (days)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Delivery Security Settings",
                "verbose_name_plural": "Delivery Security Settings",
            },
        ),
        migrations.CreateModel(
            name="DeliveryPIN",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pin_code", models.CharField(max_length=4, verbose_name="PIN Code")),
                ("pin_hash", models.CharField(max_length=128, verbose_name="PIN Hash")),
                (
                    "generated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Generated At"
                    ),
                ),
                ("valid_until", models.DateTimeField(verbose_name="Valid Until")),
                (
                    "used_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Used At"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("used", "Used"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "verification_attempts",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Verification Attempts"
                    ),
                ),
                (
                    "max_attempts",
                    models.PositiveIntegerField(default=5, verbose_name="Max Attempts"),
                ),
                (
                    "sent_via_sms",
                    models.BooleanField(default=False, verbose_name="Sent via SMS"),
                ),
                (
                    "sent_via_email",
                    models.BooleanField(default=False, verbose_name="Sent via Email"),
                ),
                (
                    "sms_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="SMS Sent At"
                    ),
                ),
                (
                    "email_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Email Sent At"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "delivery",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_pin",
                        to="delivery.deliveryrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "Delivery PIN",
                "verbose_name_plural": "Delivery PINs",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="GeofenceZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "center_latitude",
                    models.DecimalField(
                        decimal_places=8, max_digits=10, verbose_name="Center Latitude"
                    ),
                ),
                (
                    "center_longitude",
                    models.DecimalField(
                        decimal_places=8, max_digits=11, verbose_name="Center Longitude"
                    ),
                ),
                (
                    "radius_meters",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Acceptable delivery radius",
                        verbose_name="Radius (meters)",
                    ),
                ),
                (
                    "strict_mode",
                    models.BooleanField(
                        default=False,
                        help_text="Require delivery within zone",
                        verbose_name="Strict Mode",
                    ),
                ),
                (
                    "zone_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Zone Name"
                    ),
                ),
                (
                    "zone_description",
                    models.TextField(blank=True, verbose_name="Zone Description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geofence_zones",
                        to="delivery.deliveryrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "Geofence Zone",
                "verbose_name_plural": "Geofence Zones",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("otp_code", models.CharField(max_length=6, verbose_name="OTP Code")),
                (
                    "otp_hash",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="OTP Hash"
                    ),
                ),
                (
                    "customer_phone",
                    models.CharField(max_length=20, verbose_name="Customer Phone"),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Customer Email"
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Generated At"
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expires At")),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Verified At"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Verification"),
                            ("verified", "Verified"),
                            ("expired", "Expired"),
                            ("failed", "Failed Verification"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "verification_attempts",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Verification Attempts"
                    ),
                ),
                (
                    "max_attempts",
                    models.PositiveIntegerField(default=3, verbose_name="Max Attempts"),
                ),
                (
                    "delivery_latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=10,
                        null=True,
                        verbose_name="Delivery Latitude",
                    ),
                ),
                (
                    "delivery_longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=11,
                        null=True,
                        verbose_name="Delivery Longitude",
                    ),
                ),
                (
                    "verified_by_device",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Verified By Device"
                    ),
                ),
                (
                    "verified_ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Verified IP"
                    ),
                ),
                (
                    "is_suspicious",
                    models.BooleanField(default=False, verbose_name="Is Suspicious"),
                ),
                (
                    "suspicious_reason",
                    models.TextField(blank=True, verbose_name="Suspicious Reason"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otp_verifications",
                        to="delivery.deliveryrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "Delivery OTP",
                "verbose_name_plural": "Delivery OTPs",
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["delivery", "status"],
                        name="delivery_de_deliver_baa00c_idx",
                    ),
                    models.Index(
                        fields=["customer_phone", "generated_at"],
                        name="delivery_de_custome_5f4126_idx",
                    ),
                    models.Index(
                        fields=["expires_at", "status"],
                        name="delivery_de_expires_d8215a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DeliverySecurityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("otp_generated", "OTP Generated"),
                            ("otp_verified", "OTP Verified"),
                            ("otp_failed", "OTP Verification Failed"),
                            ("pin_verified", "PIN Verified"),
                            ("pin_failed", "PIN Verification Failed"),
                            ("geofence_violation", "Geofence Violation"),
                            ("geofence_success", "Geofence Verification Success"),
                            ("photo_uploaded", "Delivery Photo Uploaded"),
                            ("signature_captured", "Signature Captured"),
                            ("suspicious_activity", "Suspicious Activity Detected"),
                            ("fraud_alert", "Fraud Alert"),
                            ("security_override", "Security Check Override"),
                            ("unauthorized_access", "Unauthorized Access Attempt"),
                        ],
                        max_length=30,
                        verbose_name="Event Type",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        default="info",
                        max_length=20,
                        verbose_name="Severity",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "event_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Event Data"
                    ),
                ),
                (
                    "event_latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=10,
                        null=True,
                        verbose_name="Event Latitude",
                    ),
                ),
                (
                    "event_longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=11,
                        null=True,
                        verbose_name="Event Longitude",
                    ),
                ),
                (
                    "device_info",
                    models.TextField(blank=True, verbose_name="Device Information"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="Is Resolved"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Resolved At"
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(blank=True, verbose_name="Resolution Notes"),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "courier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_events",
                        to="delivery.courier",
                    ),
                ),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_events",
                        to="delivery.deliveryrecord",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_security_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_security_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Delivery Security Event",
                "verbose_name_plural": "Delivery Security Events",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["delivery", "event_type"],
                        name="delivery_de_deliver_874f34_idx",
                    ),
                    models.Index(
                        fields=["severity", "is_resolved"],
                        name="delivery_de_severit_946a81_idx",
                    ),
                    models.Index(
                        fields=["timestamp", "event_type"],
                        name="delivery_de_timesta_78fbf1_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FraudDetection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fraud_type",
                    models.CharField(
                        choices=[
                            ("location_mismatch", "Location Mismatch"),
                            ("time_anomaly", "Time Anomaly"),
                            ("multiple_failures", "Multiple Failed Attempts"),
                            ("suspicious_pattern", "Suspicious Pattern"),
                            (
                                "identity_verification_failed",
                                "Identity Verification Failed",
                            ),
                            ("geofence_violation", "Repeated Geofence Violations"),
                            ("duplicate_delivery", "Duplicate Delivery Attempt"),
                            ("unauthorized_recipient", "Unauthorized Recipient"),
                        ],
                        max_length=40,
                        verbose_name="Fraud Type",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low Risk"),
                            ("medium", "Medium Risk"),
                            ("high", "High Risk"),
                            ("critical", "Critical Risk"),
                        ],
                        max_length=20,
                        verbose_name="Risk Level",
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Fraud detection confidence (0-100%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Confidence Score",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "evidence",
                    models.JSONField(blank=True, default=dict, verbose_name="Evidence"),
                ),
                (
                    "detection_algorithm",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Detection Algorithm"
                    ),
                ),
                (
                    "model_version",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Model Version"
                    ),
                ),
                (
                    "is_investigated",
                    models.BooleanField(default=False, verbose_name="Is Investigated"),
                ),
                (
                    "investigated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Investigated At"
                    ),
                ),
                (
                    "investigation_notes",
                    models.TextField(blank=True, verbose_name="Investigation Notes"),
                ),
                (
                    "is_confirmed_fraud",
                    models.BooleanField(default=False, verbose_name="Confirmed Fraud"),
                ),
                (
                    "is_false_positive",
                    models.BooleanField(default=False, verbose_name="False Positive"),
                ),
                (
                    "action_taken",
                    models.TextField(blank=True, verbose_name="Action Taken"),
                ),
                (
                    "reported_to_authorities",
                    models.BooleanField(
                        default=False, verbose_name="Reported to Authorities"
                    ),
                ),
                (
                    "report_reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Report Reference"
                    ),
                ),
                (
                    "detected_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fraud_detections",
                        to="delivery.deliveryrecord",
                    ),
                ),
                (
                    "investigated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="investigated_frauds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Fraud Detection",
                "verbose_name_plural": "Fraud Detections",
                "ordering": ["-detected_at"],
                "indexes": [
                    models.Index(
                        fields=["risk_level", "is_investigated"],
                        name="delivery_fr_risk_le_de9d92_idx",
                    ),
                    models.Index(
                        fields=["is_confirmed_fraud", "detected_at"],
                        name="delivery_fr_is_conf_a736aa_idx",
                    ),
                ],
            },
        ),
    ]
