# Generated by Django 5.2.8 on 2025-12-02 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0007_orderfee"),
        ("orders", "0024_add_db_table_meta"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("cod", "Cash on Delivery (COD)"),
                    ("credit_card", "Credit Card"),
                    ("bank_transfer", "Bank Transfer"),
                    ("paypal", "PayPal"),
                    ("truvo", "Truvo Payment"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CODPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cod_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="COD Amount"
                    ),
                ),
                (
                    "collected_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Collected Amount",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="AED", max_length=3, verbose_name="Currency"
                    ),
                ),
                (
                    "collection_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Collection"),
                            ("collected", "Collected from Customer"),
                            ("deposited", "Deposited to Company"),
                            ("verified", "Verified by Finance"),
                            ("disputed", "Disputed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Collection Status",
                    ),
                ),
                (
                    "collected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Collection Date"
                    ),
                ),
                (
                    "deposited_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deposit Date"
                    ),
                ),
                (
                    "deposit_reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Deposit Reference"
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Verification Date"
                    ),
                ),
                (
                    "collection_proof_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="cod_proofs/",
                        verbose_name="Collection Proof",
                    ),
                ),
                (
                    "customer_signature",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="cod_signatures/",
                        verbose_name="Customer Signature",
                    ),
                ),
                (
                    "receipt_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Receipt Number",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=255, verbose_name="Customer Name"),
                ),
                (
                    "customer_phone",
                    models.CharField(max_length=20, verbose_name="Customer Phone"),
                ),
                ("delivery_address", models.TextField(verbose_name="Delivery Address")),
                (
                    "dispute_reason",
                    models.TextField(blank=True, verbose_name="Dispute Reason"),
                ),
                (
                    "dispute_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dispute Date"
                    ),
                ),
                (
                    "dispute_resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dispute Resolved Date"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "collected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cod_collections",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Collected By",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cod_payment",
                        to="orders.order",
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cod_details",
                        to="finance.payment",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_cod_payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Verified By",
                    ),
                ),
            ],
            options={
                "verbose_name": "COD Payment",
                "verbose_name_plural": "COD Payments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["collection_status", "collected_at"],
                        name="finance_cod_collect_f45855_idx",
                    ),
                    models.Index(
                        fields=["collected_by", "collected_at"],
                        name="finance_cod_collect_47833a_idx",
                    ),
                    models.Index(
                        fields=["collection_status", "verified_at"],
                        name="finance_cod_collect_9b1846_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CODReconciliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reconciliation_date",
                    models.DateField(verbose_name="Reconciliation Date"),
                ),
                (
                    "expected_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Expected Amount",
                    ),
                ),
                (
                    "collected_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Collected Amount",
                    ),
                ),
                (
                    "variance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Variance",
                    ),
                ),
                (
                    "total_cod_count",
                    models.IntegerField(default=0, verbose_name="Total COD Count"),
                ),
                (
                    "collected_count",
                    models.IntegerField(default=0, verbose_name="Collected Count"),
                ),
                (
                    "pending_count",
                    models.IntegerField(default=0, verbose_name="Pending Count"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("discrepancy", "Has Discrepancy"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "reconciled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Reconciled At"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "discrepancy_notes",
                    models.TextField(blank=True, verbose_name="Discrepancy Notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cod_reconciliations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Delivery Agent",
                    ),
                ),
                (
                    "reconciled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reconciled_cods",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reconciled By",
                    ),
                ),
            ],
            options={
                "verbose_name": "COD Reconciliation",
                "verbose_name_plural": "COD Reconciliations",
                "ordering": ["-reconciliation_date"],
                "unique_together": {("agent", "reconciliation_date")},
            },
        ),
    ]
