# Generated by Django 5.2.8 on 2025-12-07 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0008_alter_payment_payment_method_codpayment_and_more"),
        ("orders", "0025_return_returnitem_returnstatuslog_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "refund_reference",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Refund Reference"
                    ),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Refund Amount"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="AED", max_length=3, verbose_name="Currency"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("customer_request", "Customer Request"),
                            ("defective_product", "Defective Product"),
                            ("wrong_item", "Wrong Item Delivered"),
                            ("not_as_described", "Not as Described"),
                            ("delivery_issue", "Delivery Issue"),
                            ("duplicate_order", "Duplicate Order"),
                            ("cancelled_order", "Cancelled Order"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                        verbose_name="Reason",
                    ),
                ),
                (
                    "reason_details",
                    models.TextField(blank=True, verbose_name="Reason Details"),
                ),
                (
                    "refund_method",
                    models.CharField(
                        choices=[
                            ("original_payment", "Original Payment Method"),
                            ("bank_transfer", "Bank Transfer"),
                            ("store_credit", "Store Credit"),
                            ("cash", "Cash"),
                        ],
                        default="original_payment",
                        max_length=20,
                        verbose_name="Refund Method",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=255, verbose_name="Customer Name"),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Customer Email"
                    ),
                ),
                (
                    "customer_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Customer Phone"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approved At"
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Processed At"
                    ),
                ),
                (
                    "transaction_reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Transaction Reference"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Rejection Reason"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_refunds",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refunds",
                        to="orders.order",
                        verbose_name="Order",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refunds",
                        to="finance.payment",
                        verbose_name="Original Payment",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="finance_processed_refunds",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Processed By",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_refunds",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Requested By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Refund",
                "verbose_name_plural": "Refunds",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SellerPayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payout_reference",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Payout Reference"
                    ),
                ),
                (
                    "gross_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Gross Amount"
                    ),
                ),
                (
                    "commission_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Commission Amount",
                    ),
                ),
                (
                    "fees_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Fees Amount",
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Net Amount"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="AED", max_length=3, verbose_name="Currency"
                    ),
                ),
                ("period_start", models.DateField(verbose_name="Period Start")),
                ("period_end", models.DateField(verbose_name="Period End")),
                (
                    "orders_count",
                    models.PositiveIntegerField(default=0, verbose_name="Orders Count"),
                ),
                (
                    "payout_method",
                    models.CharField(
                        choices=[
                            ("bank_transfer", "Bank Transfer"),
                            ("cash", "Cash"),
                            ("cheque", "Cheque"),
                            ("wallet", "Wallet"),
                        ],
                        default="bank_transfer",
                        max_length=20,
                        verbose_name="Payout Method",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Bank Name"
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Account Number"
                    ),
                ),
                (
                    "iban",
                    models.CharField(blank=True, max_length=50, verbose_name="IBAN"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Processed At"
                    ),
                ),
                (
                    "transaction_reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Transaction Reference"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "failure_reason",
                    models.TextField(blank=True, verbose_name="Failure Reason"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_payouts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Processed By",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Seller",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seller Payout",
                "verbose_name_plural": "Seller Payouts",
                "ordering": ["-created_at"],
            },
        ),
    ]
