# Generated by Django 5.2.4 on 2025-07-17 20:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0001_initial'),
        ('orders', '0004_alter_order_options_remove_order_cancelled_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentperformance',
            options={'ordering': ['-date'], 'verbose_name': 'Agent Performance', 'verbose_name_plural': 'Agent Performances'},
        ),
        migrations.AlterModelOptions(
            name='calllog',
            options={'ordering': ['-call_time'], 'verbose_name': 'Call Log', 'verbose_name_plural': 'Call Logs'},
        ),
        migrations.RemoveField(
            model_name='agentperformance',
            name='calls_made',
        ),
        migrations.RemoveField(
            model_name='agentperformance',
            name='successful_confirmations',
        ),
        migrations.AddField(
            model_name='agentperformance',
            name='break_time_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='Break Time (minutes)'),
        ),
        migrations.AddField(
            model_name='agentperformance',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='agentperformance',
            name='customer_satisfaction_avg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Average Customer Satisfaction'),
        ),
        migrations.AddField(
            model_name='agentperformance',
            name='first_call_resolution_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='First Call Resolution Rate (%)'),
        ),
        migrations.AddField(
            model_name='agentperformance',
            name='orders_cancelled',
            field=models.PositiveIntegerField(default=0, verbose_name='Orders Cancelled'),
        ),
        migrations.AddField(
            model_name='agentperformance',
            name='orders_confirmed',
            field=models.PositiveIntegerField(default=0, verbose_name='Orders Confirmed'),
        ),
        migrations.AddField(
            model_name='agentperformance',
            name='orders_postponed',
            field=models.PositiveIntegerField(default=0, verbose_name='Orders Postponed'),
        ),
        migrations.AddField(
            model_name='agentperformance',
            name='resolution_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Resolution Rate (%)'),
        ),
        migrations.AddField(
            model_name='agentperformance',
            name='successful_calls',
            field=models.PositiveIntegerField(default=0, verbose_name='Successful Calls'),
        ),
        migrations.AddField(
            model_name='agentperformance',
            name='total_calls_made',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Calls Made'),
        ),
        migrations.AddField(
            model_name='agentperformance',
            name='total_orders_handled',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Orders Handled'),
        ),
        migrations.AddField(
            model_name='agentperformance',
            name='total_work_time_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Work Time (minutes)'),
        ),
        migrations.AddField(
            model_name='agentperformance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='calllog',
            name='call_recording_url',
            field=models.URLField(blank=True, verbose_name='Call Recording URL'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='calllog',
            name='customer_satisfaction',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Customer Satisfaction'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='escalation_reason',
            field=models.TextField(blank=True, verbose_name='Escalation Reason'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='follow_up_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Follow Up Date'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='resolution_status',
            field=models.CharField(choices=[('resolved', 'Resolved'), ('pending', 'Pending'), ('escalated', 'Escalated'), ('follow_up_required', 'Follow Up Required')], default='pending', max_length=20, verbose_name='Resolution Status'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='agentperformance',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agentperformance',
            name='average_call_duration',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Average Call Duration (minutes)'),
        ),
        migrations.AlterField(
            model_name='agentperformance',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='call_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Call Time'),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='duration',
            field=models.PositiveIntegerField(default=0, verbose_name='Duration (seconds)'),
        ),
        # Removed: migrations.AlterField for CallLog.id from BigAutoField to UUIDField
        # This causes PostgreSQL errors - cannot cast bigint to uuid
        # Keeping BigAutoField for CallLog.id
        migrations.AlterField(
            model_name='calllog',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Call Notes'),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('wrong_number', 'Wrong Number'), ('voicemail', 'Voicemail'), ('call_back', 'Call Back Requested'), ('escalated', 'Escalated')], max_length=20, verbose_name='Call Status'),
        ),
        migrations.CreateModel(
            name='CallCenterAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True, verbose_name='Employee ID')),
                ('phone_extension', models.CharField(blank=True, max_length=10, verbose_name='Phone Extension')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('on_leave', 'On Leave')], default='active', max_length=20, verbose_name='Status')),
                ('availability', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('break', 'On Break'), ('offline', 'Offline'), ('training', 'In Training')], default='offline', max_length=20, verbose_name='Availability')),
                ('max_concurrent_orders', models.PositiveIntegerField(default=5, verbose_name='Max Concurrent Orders')),
                ('current_orders_count', models.PositiveIntegerField(default=0, verbose_name='Current Orders Count')),
                ('team', models.CharField(blank=True, max_length=100, verbose_name='Team')),
                ('skills', models.JSONField(default=list, verbose_name='Skills')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_agents', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='call_center_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Call Center Agent',
                'verbose_name_plural': 'Call Center Agents',
                'ordering': ['user__full_name'],
            },
        ),
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Login Time')),
                ('logout_time', models.DateTimeField(blank=True, null=True, verbose_name='Logout Time')),
                ('status', models.CharField(choices=[('active', 'Active'), ('break', 'Break'), ('offline', 'Offline')], default='active', max_length=20, verbose_name='Status')),
                ('workstation_id', models.CharField(blank=True, max_length=50, verbose_name='Workstation ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Last Activity')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='callcenter.callcenteragent')),
            ],
            options={
                'verbose_name': 'Agent Session',
                'verbose_name_plural': 'Agent Sessions',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='CustomerInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('call', 'Phone Call'), ('email', 'Email'), ('chat', 'Live Chat'), ('follow_up', 'Follow Up'), ('escalation', 'Escalation')], max_length=20, verbose_name='Interaction Type')),
                ('interaction_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Interaction Time')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='Duration (minutes)')),
                ('resolution_status', models.CharField(choices=[('resolved', 'Resolved'), ('pending', 'Pending'), ('escalated', 'Escalated'), ('follow_up_required', 'Follow Up Required')], default='pending', max_length=20, verbose_name='Resolution Status')),
                ('interaction_notes', models.TextField(blank=True, verbose_name='Interaction Notes')),
                ('customer_satisfaction', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Customer Satisfaction')),
                ('follow_up_date', models.DateTimeField(blank=True, null=True, verbose_name='Follow Up Date')),
                ('escalation_reason', models.TextField(blank=True, verbose_name='Escalation Reason')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_interactions', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_interactions', to='orders.order')),
            ],
            options={
                'verbose_name': 'Customer Interaction',
                'verbose_name_plural': 'Customer Interactions',
                'ordering': ['-interaction_time'],
            },
        ),
        migrations.CreateModel(
            name='ManagerNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.TextField(verbose_name='Note Text')),
                ('note_type', models.CharField(choices=[('instruction', 'Instruction'), ('reminder', 'Reminder'), ('priority', 'Priority'), ('escalation', 'Escalation'), ('feedback', 'Feedback')], default='instruction', max_length=20, verbose_name='Note Type')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='Urgent')),
                ('is_read_by_agent', models.BooleanField(default=False, verbose_name='Read by Agent')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_received', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_notes', to='orders.order')),
            ],
            options={
                'verbose_name': 'Manager Note',
                'verbose_name_plural': 'Manager Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Assignment Date')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10, verbose_name='Priority')),
                ('expected_completion', models.DateTimeField(blank=True, null=True, verbose_name='Expected Completion')),
                ('assignment_notes', models.TextField(blank=True, verbose_name='Assignment Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Assignment')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_orders', to=settings.AUTH_USER_MODEL)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_assignments_made', related_query_name='assignment_made', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_center_assignments', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Assignment',
                'verbose_name_plural': 'Order Assignments',
                'ordering': ['-assignment_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(max_length=50, verbose_name='Previous Status')),
                ('new_status', models.CharField(max_length=50, verbose_name='New Status')),
                ('status_change_reason', models.TextField(blank=True, verbose_name='Status Change Reason')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='Cancellation Reason')),
                ('change_timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Change Timestamp')),
                ('customer_notified', models.BooleanField(default=False, verbose_name='Customer Notified')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Status History',
                'verbose_name_plural': 'Order Status Histories',
                'ordering': ['-change_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TeamPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100, verbose_name='Team Name')),
                ('date', models.DateField(verbose_name='Date')),
                ('total_agents', models.PositiveIntegerField(default=0, verbose_name='Total Agents')),
                ('active_agents', models.PositiveIntegerField(default=0, verbose_name='Active Agents')),
                ('total_orders_handled', models.PositiveIntegerField(default=0, verbose_name='Total Orders Handled')),
                ('orders_confirmed', models.PositiveIntegerField(default=0, verbose_name='Orders Confirmed')),
                ('orders_cancelled', models.PositiveIntegerField(default=0, verbose_name='Orders Cancelled')),
                ('average_handle_time', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Average Handle Time (minutes)')),
                ('team_confirmation_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Team Confirmation Rate (%)')),
                ('team_satisfaction_avg', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Team Satisfaction Average')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('top_performer_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_performer_records', to=settings.AUTH_USER_MODEL, verbose_name='Top Performer')),
            ],
            options={
                'verbose_name': 'Team Performance',
                'verbose_name_plural': 'Team Performances',
                'ordering': ['-date'],
                'unique_together': {('team_name', 'date')},
            },
        ),
    ]
