# Generated by Django 5.2.4 on 2025-07-18 12:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0003_remove_callcenteragent_supervisor_and_more'),
        ('orders', '0004_alter_order_options_remove_order_cancelled_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calllog',
            options={'ordering': ['-call_time'], 'verbose_name': 'Call Log', 'verbose_name_plural': 'Call Logs'},
        ),
        migrations.AddField(
            model_name='calllog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='calllog',
            name='customer_satisfaction',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Customer Satisfaction'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='escalation_reason',
            field=models.TextField(blank=True, verbose_name='Escalation Reason'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='follow_up_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Follow Up Date'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='resolution_status',
            field=models.CharField(choices=[('resolved', 'Resolved'), ('pending', 'Pending'), ('escalated', 'Escalated'), ('follow_up_required', 'Follow Up Required')], default='pending', max_length=20, verbose_name='Resolution Status'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='agentperformance',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='agentperformance',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='call_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Call Time'),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='duration',
            field=models.PositiveIntegerField(default=0, verbose_name='Duration (seconds)'),
        ),
        # Removed: migrations.AlterField for CallLog.id from BigAutoField to UUIDField
        # This causes PostgreSQL errors - cannot cast bigint to uuid
        # Keeping BigAutoField for CallLog.id
        migrations.AlterField(
            model_name='calllog',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Call Notes'),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('wrong_number', 'Wrong Number'), ('voicemail', 'Voicemail'), ('call_back', 'Call Back Requested'), ('escalated', 'Escalated')], max_length=20, verbose_name='Call Status'),
        ),
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('break', 'On Break'), ('offline', 'Offline'), ('training', 'In Training')], default='offline', max_length=20)),
                ('concurrent_orders', models.PositiveIntegerField(default=0)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('workstation_id', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent Session',
                'verbose_name_plural': 'Agent Sessions',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='CustomerInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('chat', 'Chat'), ('follow_up', 'Follow Up')], max_length=20)),
                ('interaction_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('resolution_status', models.CharField(choices=[('resolved', 'Resolved'), ('pending', 'Pending'), ('escalated', 'Escalated'), ('follow_up_required', 'Follow Up Required')], default='pending', max_length=20)),
                ('interaction_notes', models.TextField(blank=True)),
                ('customer_satisfaction', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_interactions', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions_received', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_interactions', to='orders.order')),
            ],
            options={
                'verbose_name': 'Customer Interaction',
                'verbose_name_plural': 'Customer Interactions',
                'ordering': ['-interaction_time'],
            },
        ),
        migrations.CreateModel(
            name='ManagerNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.TextField()),
                ('note_type', models.CharField(choices=[('instruction', 'Instruction'), ('reminder', 'Reminder'), ('priority', 'Priority'), ('escalation', 'Escalation')], default='instruction', max_length=20)),
                ('is_urgent', models.BooleanField(default=False)),
                ('is_read_by_agent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_received', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_notes', to='orders.order')),
            ],
            options={
                'verbose_name': 'Manager Note',
                'verbose_name_plural': 'Manager Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('manager_notes', models.TextField(blank=True)),
                ('priority_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('expected_completion', models.DateTimeField(blank=True, null=True)),
                ('assignment_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_orders', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='orders.order')),
                ('previous_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order Assignment',
                'verbose_name_plural': 'Order Assignments',
                'ordering': ['-assignment_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(max_length=50)),
                ('new_status', models.CharField(max_length=50)),
                ('status_change_reason', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('change_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer_notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Status History',
                'verbose_name_plural': 'Order Status Histories',
                'ordering': ['-change_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TeamPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField()),
                ('total_agents', models.PositiveIntegerField(default=0)),
                ('orders_handled', models.PositiveIntegerField(default=0)),
                ('orders_confirmed', models.PositiveIntegerField(default=0)),
                ('orders_cancelled', models.PositiveIntegerField(default=0)),
                ('average_handle_time', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('team_confirmation_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('team_satisfaction_avg', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lowest_performer_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lowest_performances', to=settings.AUTH_USER_MODEL)),
                ('top_performer_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_performances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team Performance',
                'verbose_name_plural': 'Team Performances',
                'ordering': ['-date'],
                'unique_together': {('team', 'date')},
            },
        ),
    ]
