"""
Django settings for crm_fulfillment project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-p6(d1x^*0xb*d)a_hn3iubcl_wen!i4+80*o32=_9pdadls9j!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Debug messages
TEMPLATE_DEBUG = DEBUG

ALLOWED_HOSTS = ["*"]

# Email Configuration
# Email Configuration for Hostinger (can be overridden by environment variables)
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.hostinger.com')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'fill it by self')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', 'fill it by self')

EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '465'))
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'True') == 'True'
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'False') == 'True'
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'fill it by self')



# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    # REST Framework
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    # Cloudinary
    'cloudinary',
    'cloudinary_storage',
    # Security packages
    'axes',  # Login attempt tracking and lockout
    'django_otp',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_static',
    # Celery
    'django_celery_beat',
    'django_celery_results',
    # Custom apps
    'dashboard',
    'users',
    'sellers',
    'sourcing',
    'inventory',
    'callcenter',
    'callcenter_manager',
    'callcenter_agent',
    'order_packaging',
    'delivery',
    'finance',
    'settings',
    'orders',
    'landing',
    'products',
    'subscribers',
    'roles',
    'bug_reports',
    'stock_keeper',
    'notifications',
    'analytics',  # Analytics and KPIs
]


AUTH_USER_MODEL = 'users.User'

# TAILWIND_APP_NAME = 'theme'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'landing.middleware.LandingLanguageMiddleware',  # Custom middleware for landing pages language
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',  # OTP middleware for 2FA
    'axes.middleware.AxesMiddleware',  # Login attempt tracking
    'users.middleware_2fa.TwoFactorAuthMiddleware',
    'order_packaging.middleware.PackagingAgentAccessMiddleware',  # Restrict Packaging Agent to packaging URLs only
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Authentication backends for axes
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',  # Axes backend for login tracking
    'django.contrib.auth.backends.ModelBackend',  # Default Django backend
]

ROOT_URLCONF = 'crm_fulfillment.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
            ],
        },
    },
]

WSGI_APPLICATION = 'crm_fulfillment.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Support for environment-based database configuration (Docker)
DATABASE_TYPE = os.environ.get('DATABASE', 'postgres').lower()

if DATABASE_TYPE == 'postgres':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'atlas_crm'),
            'USER': os.environ.get('DB_USER', 'atlas_user'),
            'PASSWORD': os.environ.get('DB_PASSWORD', 'atlas_secure_pass_2024'),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5433'),
        }
    }
else:
    # Default to SQLite for local development
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en'

USE_I18N = True
USE_L10N = False
USE_TZ = True

LANGUAGES = [
    ('en', 'English'),
    ('ar', 'Arabic'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

# Language settings - keeping for compatibility but not used
LANGUAGE_COOKIE_NAME = 'django_language'
LANGUAGE_COOKIE_AGE = 60 * 60 * 24 * 365  # 1 year


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Cloudinary Configuration
# IMPORTANT: Replace 'YOUR_CLOUD_NAME_HERE' with your actual Cloudinary Cloud Name from dashboard
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': 'fill it by self',
    'API_KEY': 'fill it by self',
    'API_SECRET': 'fill it by self',
    # Ensure secure URLs are used
    'SECURE': True,
    # Use HTTPS for all Cloudinary URLs
    'API_PROXY': None,
}

# Media files - Use Cloudinary for all media storage
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
# MEDIA_URL should be empty or not set when using Cloudinary
# Cloudinary Storage generates full URLs automatically
MEDIA_URL = ''
# MEDIA_ROOT is not needed when using Cloudinary, but kept for backward compatibility
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication settings
LOGIN_URL = 'users:login'
# LOGIN_REDIRECT_URL is now handled in the login view based on user role
LOGIN_REDIRECT_URL = 'dashboard:index'
LOGOUT_REDIRECT_URL = 'users:login'

# Add this setting to define if the default language should have a prefix in URLs
PREFIX_DEFAULT_LANGUAGE = False

# Site URL for generating absolute URLs (used in bug reports)
SITE_URL = os.environ.get('SITE_URL', 'http://127.0.0.1:8000')  # Change this to your production domain

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # Next.js development server
    "http://127.0.0.1:3000",
]

CORS_ALLOW_CREDENTIALS = True

# Session Configuration
SESSION_COOKIE_HTTPONLY = False  # Allow JavaScript access for debugging
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
SESSION_COOKIE_SAMESITE = 'Lax'  # Allow cross-site requests
SESSION_SAVE_EVERY_REQUEST = True  # Save session on every request

CORS_ALLOWED_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# CSRF Trusted Origins
CSRF_TRUSTED_ORIGINS = [
    "https://atlas-crmsystem.codixverse.cloud",
    "http://atlas-crmsystem.codixverse.cloud",
    "https://atlas.alexandratechlab.com",
    "http://atlas.alexandratechlab.com",
    "http://localhost:8070",
    "http://127.0.0.1:8070",
]

# Site URL for generating absolute URLs
SITE_URL = os.environ.get('SITE_URL', 'https://atlas.alexandratechlab.com')

# ============================================
# SECURITY CONFIGURATION
# ============================================

# Django-Axes Configuration (Login attempt tracking and lockout)
AXES_FAILURE_LIMIT = 5  # Lock out after 5 failed attempts
AXES_COOLOFF_TIME = 1  # Lock out for 1 hour (in hours)
AXES_LOCKOUT_TEMPLATE = 'axes/account_locked.html'
AXES_RESET_ON_SUCCESS = True  # Reset failed attempts on successful login
AXES_ENABLE_ACCESS_FAILURE_LOG = True
AXES_VERBOSE = True
AXES_LOCKOUT_CALLABLE = None
AXES_IPWARE_PROXY_ORDER = 'left-most'
AXES_IPWARE_META_PRECEDENCE_ORDER = [
    'HTTP_X_FORWARDED_FOR',
    'REMOTE_ADDR',
]

# Rate Limiting Configuration
RATELIMIT_ENABLE = True
RATELIMIT_USE_CACHE = 'default'
RATELIMIT_FAIL_OPEN = False

# Security Headers
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'SAMEORIGIN'

# Session Security
SESSION_COOKIE_AGE = 60 * 60 * 8  # 8 hours
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True

# ============================================
# CELERY CONFIGURATION
# ============================================

# Redis Configuration
REDIS_HOST = os.environ.get('REDIS_HOST', 'localhost')
REDIS_PORT = os.environ.get('REDIS_PORT', '6379')
REDIS_URL = f'redis://{REDIS_HOST}:{REDIS_PORT}'

# Celery Configuration
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', f'{REDIS_URL}/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'django-db')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Cache Configuration
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': f'{REDIS_URL}/1',
        'KEY_PREFIX': 'atlas_crm',
        'TIMEOUT': 300,  # 5 minutes default
    },
    'axes': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': f'{REDIS_URL}/2',
    }
}

# Axes Cache Backend
AXES_CACHE = 'axes'

# ============================================
# LOGGING CONFIGURATION
# ============================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'atlas_crm.log'),
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'security_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'security.log'),
            'maxBytes': 1024 * 1024 * 5,
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.security': {
            'handlers': ['security_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'axes': {
            'handlers': ['security_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'atlas_crm': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}