# Generated by Django 5.2 on 2025-05-12 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packaging_started', models.DateTimeField(auto_now_add=True)),
                ('packaging_completed', models.DateTimeField(blank=True, null=True)),
                ('packaging_notes', models.TextField(blank=True)),
                ('package_type', models.CharField(max_length=50)),
                ('package_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=50)),
                ('barcode', models.CharField(max_length=100, unique=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_packaging', to='orders.order')),
            ],
        ),
    ]
