# Generated by Django 5.2.4 on 2025-07-18 12:51

import django.db.models.deletion
import order_packaging.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_deliverycompany_options_and_more'),
        ('orders', '0004_alter_order_options_remove_order_cancelled_reason_and_more'),
        ('order_packaging', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('material_type', models.CharField(choices=[('box', 'Box'), ('envelope', 'Envelope'), ('polybag', 'Polybag'), ('tape', 'Tape'), ('bubble_wrap', 'Bubble Wrap'), ('filler', 'Filler Material'), ('label', 'Label'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('current_stock', models.PositiveIntegerField(default=0)),
                ('min_stock_level', models.PositiveIntegerField(default=10)),
                ('unit', models.CharField(default='pieces', max_length=20)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('supplier', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Packaging Material',
                'verbose_name_plural': 'Packaging Materials',
                'ordering': ['material_type', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='packagingrecord',
            options={'ordering': ['-packaging_started'], 'verbose_name': 'Packaging Record', 'verbose_name_plural': 'Packaging Records'},
        ),
        migrations.AddField(
            model_name='packagingrecord',
            name='courier_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.courier'),
        ),
        migrations.AddField(
            model_name='packagingrecord',
            name='materials_used',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='packagingrecord',
            name='quality_check_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_checked_packages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='packagingrecord',
            name='quality_check_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packagingrecord',
            name='quality_check_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='packagingrecord',
            name='shipping_label_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='packagingrecord',
            name='shipping_label_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='packagingrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='packagingrecord',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='packagingrecord',
            name='barcode',
            field=models.CharField(default=order_packaging.models.generate_package_barcode, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='packagingrecord',
            name='package_type',
            field=models.CharField(choices=[('box', 'Box'), ('envelope', 'Envelope'), ('polybag', 'Polybag'), ('tube', 'Tube'), ('custom', 'Custom')], default='box', max_length=20),
        ),
        migrations.AlterField(
            model_name='packagingrecord',
            name='packager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaged_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PackagingQualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('visual', 'Visual Inspection'), ('weight', 'Weight Verification'), ('dimensions', 'Dimensions Check'), ('label', 'Label Verification'), ('seal', 'Seal Integrity'), ('other', 'Other')], max_length=20)),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('conditional', 'Conditional Pass')], max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('checker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performed_quality_checks', to=settings.AUTH_USER_MODEL)),
                ('packaging_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='order_packaging.packagingrecord')),
            ],
            options={
                'verbose_name': 'Packaging Quality Check',
                'verbose_name_plural': 'Packaging Quality Checks',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='PackagingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=15)),
                ('estimated_duration', models.PositiveIntegerField(default=15)),
                ('actual_duration', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_packaging_tasks', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_tasks', to='orders.order')),
            ],
            options={
                'verbose_name': 'Packaging Task',
                'verbose_name_plural': 'Packaging Tasks',
                'ordering': ['-priority', 'created_at'],
            },
        ),
    ]
