# Generated by Django 5.0.2 on 2025-09-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_packaging', '0003_packagingmaterial_alter_packagingrecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagingrecord',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='packagingrecord',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='packagingrecord',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
