# Generated by Django 5.2.8 on 2025-12-01 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_packaging", "0005_rename_tables"),
        ("orders", "0024_add_db_table_meta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packagingqualitycheck",
            name="packaging_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quality_checks",
                to="order_packaging.packagingrecord",
            ),
        ),
        migrations.AlterField(
            model_name="packagingrecord",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="packaging",
                to="orders.order",
            ),
        ),
        migrations.AlterModelTable(
            name="packagingmaterial",
            table="packaging_packagingmaterial",
        ),
        migrations.AlterModelTable(
            name="packagingqualitycheck",
            table="packaging_packagingqualitycheck",
        ),
        migrations.AlterModelTable(
            name="packagingrecord",
            table="packaging_packagingrecord",
        ),
        migrations.AlterModelTable(
            name="packagingtask",
            table="packaging_packagingtask",
        ),
    ]
