# Generated by Django 5.2.1 on 2025-05-20 16:04

import django.db.models.deletion
import django.utils.timezone
import orders.models
import uuid
from django.conf import settings
from django.db import migrations, models


def simple_order_code():
    """Simple order code generator for migrations"""
    import random
    from django.utils import timezone
    today = timezone.now().date()
    date_part = f"{today.year % 100:02d}{today.month:02d}{today.day:02d}"
    return f"#{date_part}{random.randint(1, 999):03d}"


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_initial'),
        ('products', '0001_initial'),
        ('sellers', '0003_seller'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='cancelled_reason',
        ),
        migrations.RemoveField(
            model_name='order',
            name='code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_company',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='order',
            name='postponed_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sales_channel',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tracking_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Order Date'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_code',
            field=models.CharField(default=simple_order_code, max_length=50, unique=True, verbose_name='Order Code'),
        ),
        migrations.AddField(
            model_name='order',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price Per Unit'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='products.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Seller Email'),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Seller Phone'),
        ),
        migrations.AddField(
            model_name='order',
            name='store_link',
            field=models.URLField(blank=True, verbose_name='Store Link'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Customer Phone'),
        ),
        migrations.AlterField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='sellers.seller', verbose_name='Seller'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
