# Generated by Django 5.2.8 on 2025-12-01 13:00

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0023_order_no_answer_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_code",
            field=models.CharField(
                default=orders.models.generate_order_code,
                max_length=50,
                unique=True,
                verbose_name="Order Code",
            ),
        ),
    ]
