# Generated by Django 5.2.8 on 2025-12-02 14:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0024_add_db_table_meta"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Return",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "return_code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Return Code"
                    ),
                ),
                (
                    "return_reason",
                    models.CharField(
                        choices=[
                            ("damaged", "Product Damaged"),
                            ("defective", "Product Defective/Not Working"),
                            ("wrong_item", "Wrong Item Delivered"),
                            ("not_as_described", "Not As Described"),
                            ("size_issue", "Size/Fit Issue"),
                            ("quality_issue", "Quality Issue"),
                            ("customer_regret", "Customer Changed Mind"),
                            ("duplicate_order", "Duplicate Order"),
                            ("late_delivery", "Late Delivery"),
                            ("other", "Other Reason"),
                        ],
                        max_length=30,
                        verbose_name="Return Reason",
                    ),
                ),
                (
                    "return_description",
                    models.TextField(
                        help_text="Detailed explanation of the return reason",
                        verbose_name="Detailed Description",
                    ),
                ),
                (
                    "return_status",
                    models.CharField(
                        choices=[
                            ("requested", "Return Requested"),
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("pickup_scheduled", "Pickup Scheduled"),
                            ("in_transit", "In Transit to Warehouse"),
                            ("received", "Received at Warehouse"),
                            ("inspecting", "Under Inspection"),
                            ("inspected", "Inspection Completed"),
                            ("approved_for_refund", "Approved for Refund"),
                            ("refund_processing", "Refund Processing"),
                            ("refund_completed", "Refund Completed"),
                            ("restocked", "Item Restocked"),
                            ("completed", "Return Completed"),
                            ("cancelled", "Return Cancelled"),
                        ],
                        default="requested",
                        max_length=30,
                        verbose_name="Return Status",
                    ),
                ),
                (
                    "return_photo_1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="returns/photos/",
                        verbose_name="Return Photo 1",
                    ),
                ),
                (
                    "return_photo_2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="returns/photos/",
                        verbose_name="Return Photo 2",
                    ),
                ),
                (
                    "return_photo_3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="returns/photos/",
                        verbose_name="Return Photo 3",
                    ),
                ),
                (
                    "return_video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="returns/videos/",
                        verbose_name="Return Video Evidence",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approved At"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Rejection Reason"),
                ),
                (
                    "return_tracking_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Return Tracking Number",
                    ),
                ),
                (
                    "return_carrier",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Return Carrier"
                    ),
                ),
                (
                    "pickup_scheduled_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Pickup Scheduled Date"
                    ),
                ),
                (
                    "pickup_address",
                    models.TextField(blank=True, verbose_name="Pickup Address"),
                ),
                (
                    "received_at_warehouse",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Received at Warehouse"
                    ),
                ),
                (
                    "inspection_started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Inspection Started"
                    ),
                ),
                (
                    "inspection_completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Inspection Completed"
                    ),
                ),
                (
                    "item_condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excellent", "Excellent - Like New"),
                            ("good", "Good - Minor Wear"),
                            ("fair", "Fair - Noticeable Wear"),
                            ("poor", "Poor - Significant Damage"),
                            ("damaged", "Damaged - Not Resellable"),
                            ("defective", "Defective/Not Working"),
                            ("opened", "Opened Package Only"),
                            ("unopened", "Unopened Package"),
                        ],
                        max_length=20,
                        verbose_name="Item Condition",
                    ),
                ),
                (
                    "inspection_notes",
                    models.TextField(blank=True, verbose_name="Inspection Notes"),
                ),
                (
                    "inspection_photos",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Inspection Photos URLs"
                    ),
                ),
                (
                    "can_restock",
                    models.BooleanField(default=False, verbose_name="Can Be Restocked"),
                ),
                (
                    "restocked",
                    models.BooleanField(default=False, verbose_name="Item Restocked"),
                ),
                (
                    "restocked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Restocked At"
                    ),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Refund Amount (AED)",
                    ),
                ),
                (
                    "refund_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("original_payment", "Original Payment Method"),
                            ("bank_transfer", "Bank Transfer"),
                            ("store_credit", "Store Credit"),
                            ("cash", "Cash"),
                            ("wallet", "Wallet/Account Balance"),
                        ],
                        max_length=30,
                        verbose_name="Refund Method",
                    ),
                ),
                (
                    "refund_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("partial", "Partial Refund"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Refund Status",
                    ),
                ),
                (
                    "refund_processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Refund Processed At"
                    ),
                ),
                (
                    "refund_reference",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Refund Reference Number",
                    ),
                ),
                (
                    "refund_notes",
                    models.TextField(blank=True, verbose_name="Refund Notes"),
                ),
                (
                    "restocking_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Restocking Fee (AED)",
                    ),
                ),
                (
                    "damage_deduction",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Damage Deduction (AED)",
                    ),
                ),
                (
                    "shipping_cost_deduction",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Shipping Cost Deduction (AED)",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Higher number = higher priority",
                        verbose_name="Priority Level",
                    ),
                ),
                (
                    "requires_manager_approval",
                    models.BooleanField(
                        default=False, verbose_name="Requires Manager Approval"
                    ),
                ),
                (
                    "customer_contacted",
                    models.BooleanField(
                        default=False, verbose_name="Customer Contacted"
                    ),
                ),
                (
                    "customer_contact_notes",
                    models.TextField(blank=True, verbose_name="Customer Contact Notes"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Return Requested At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Return Completed At"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_returns",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="returns",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Customer",
                    ),
                ),
                (
                    "inspector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inspected_returns",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Inspector",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="returns",
                        to="orders.order",
                        verbose_name="Order",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_returns",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Received By",
                    ),
                ),
                (
                    "refund_processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_refunds",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Refund Processed By",
                    ),
                ),
                (
                    "restocked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="restocked_returns",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Restocked By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Return",
                "verbose_name_plural": "Returns",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReturnItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(verbose_name="Quantity to Return"),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("damaged", "Product Damaged"),
                            ("defective", "Product Defective/Not Working"),
                            ("wrong_item", "Wrong Item Delivered"),
                            ("not_as_described", "Not As Described"),
                            ("size_issue", "Size/Fit Issue"),
                            ("quality_issue", "Quality Issue"),
                            ("customer_regret", "Customer Changed Mind"),
                            ("duplicate_order", "Duplicate Order"),
                            ("late_delivery", "Late Delivery"),
                            ("other", "Other Reason"),
                        ],
                        max_length=30,
                        verbose_name="Item Return Reason",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excellent", "Excellent - Like New"),
                            ("good", "Good - Minor Wear"),
                            ("fair", "Fair - Noticeable Wear"),
                            ("poor", "Poor - Significant Damage"),
                            ("damaged", "Damaged - Not Resellable"),
                            ("defective", "Defective/Not Working"),
                            ("opened", "Opened Package Only"),
                            ("unopened", "Unopened Package"),
                        ],
                        max_length=20,
                        verbose_name="Item Condition",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Item Notes")),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.orderitem",
                        verbose_name="Order Item",
                    ),
                ),
                (
                    "return_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.return",
                        verbose_name="Return",
                    ),
                ),
            ],
            options={
                "verbose_name": "Return Item",
                "verbose_name_plural": "Return Items",
            },
        ),
        migrations.CreateModel(
            name="ReturnStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Old Status"
                    ),
                ),
                (
                    "new_status",
                    models.CharField(max_length=30, verbose_name="New Status"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Timestamp"
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Changed By",
                    ),
                ),
                (
                    "return_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="orders.return",
                        verbose_name="Return",
                    ),
                ),
            ],
            options={
                "verbose_name": "Return Status Log",
                "verbose_name_plural": "Return Status Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="return",
            index=models.Index(
                fields=["return_code"], name="orders_retu_return__d371f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="return",
            index=models.Index(
                fields=["return_status"], name="orders_retu_return__c2309a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="return",
            index=models.Index(
                fields=["refund_status"], name="orders_retu_refund__3276f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="return",
            index=models.Index(
                fields=["created_at"], name="orders_retu_created_0e471a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="return",
            index=models.Index(fields=["order"], name="orders_retu_order_i_ff98ce_idx"),
        ),
    ]
